name: Check branch

on:
  push:
    branches: [improve-tooling]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
        options: >-
          --restart=always
          --name registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - uses: pnpm/action-setup@v4
#        name: Install pnpm
#        with:
#          run_install: false
#
#      - name: Install Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: '.nvmrc'
#          cache: 'pnpm'
#
#      - name: Install dependencies
#        run: pnpm install
#
#      - name: Run tests
#        run: pnpm test

      - name: Test Docker commands
        run: |
          docker pull busybox
          docker tag busybox localhost:5000/busybox
          docker push localhost:5000/busybox
          docker rmi busybox
          docker pull localhost:5000/busybox
          docker run -it --rm localhost:5000/busybox echo "Hello, world!"
#          docker save busybox | gzip > busybox.tar.gz
#          ls -al
