name: Check pull request

on:
  pull_request:
    branches:
      - master

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
        options: >-
          --restart=always
          --name registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Check formatting
        run: pnpm prettier --check .

      - name: Lint
        run: pnpm eslint .

      - name: Build
        run: pnpm build

      - name: Run tests
        env:
          REGISTRY_URL: 'http://localhost:5000'
        run: pnpm test -- --coverage

      - name: Report Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: davelosert/vitest-coverage-report-action@v2
